# This scheme assigns all characters to a single race (except ghouls). Useful for checking
# a race out--set the race below, then use the furrifier's "Roll" button to see how it
# looks on different characters. 

class_match = [
    ["CLASS_GHOUL", "RACE", "GhoulRace"],   # Repeat so that ghouls are filtered out first
    ["CLASS_ALL", "FACTION", "*"],          # No distinction between characters.
]

[[class_probabilities]]
class = "CLASS_ALL"
races = [
  ["FFODeerRace", 100], 
]

[[class_probabilities]]
class = "CLASS_GHOUL"
races = [
  ["FFOSnekdogRace", 100],
]
